import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpeg',
      price: 80,
      brand: 'Adidas',
      rating: 3.2,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 50,
      brand: 'Raymond',
      rating: 4.1,
      numReviews: 7,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Golf Shirt',
      slug: 'golf-shirt',
      category: 'Shirts',
      image: '/images/shirt4.jpg',
      price: 100,
      brand: 'Puma',
      rating: 3.0,
      numReviews: 15,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Biker Jacket',
      slug: 'biker-jacket',
      category: 'Jacket',
      image: '/images/jacket1.jpg',
      price: 200,
      brand: 'Puma',
      rating: 4.8,
      numReviews: 11,
      countInStock: 23,
      description: 'A popular jacket',
    },
    {
      name: 'Denim Jeans',
      slug: 'denim-jeans',
      category: 'Jeans',
      image: '/images/jeans1.jpg',
      price: 50,
      brand: 'Adidas',
      rating: 5.0,
      numReviews: 6,
      countInStock: 20,
      description: 'A popular jeans',
    },
  ],
};

export default data;
